# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: Loneliness is the carnival of one single soul.
- content: KEEP CALM and CARRY ON.
bottom_saying: I'm still learning …
# Content
excerpt_link: More
fancybox: true # this theme do not support fancybox

rss: 

highlightjs: github

#Works
works:
- works_name: 冠影
  works_url: http://www.filmboard.cn/
- works_name: 扇贝青梅小组查卡程序
  works_url: http://139.199.189.124:3000/

#duoshuo name
duoshuo: king

#disqus name
disqus_shortname: 

# Miscellaneous
github: https://github.com/xmoyKing
# twitter: https://twitter.com/
# facebook: https://www.facebook.com/
# google: https://google.com/
# weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: Joined GitHub - on April 26, 2013 
- num: 2
  word: Studying as a FE - on November 1, 2014
- num: 3
  word: Change to Hexo - on January 18, 2017
- num: 4
  word: More

#Links
links:
- name: 308-USTC
  link: https://github.com/308-USTC
- name: motivated_Dou / Mr24 
  link: http://www.cnblogs.com/Mr24/
- name: Sherry-Zhang
  link: http://Sherry-Zhang.github.io/
- name: Hexo文档
  link: https://hexo.io/zh-cn/docs/index.html